<?php

//公共模块访问及操作权限
return array(
    'newsView' => array(//浏览新闻
        '游客' => True,
        '校友(未审核)' => True,
        '冻结' => True,
        '校友(已认证)' => True,
        '未通过认证' => True,
        '管理员' => True,
    ),
    'newsPublish' => array(//发布新闻
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'aaHomeView' => array(//浏览校友会主页
        '游客' => True,
        '未通过认证' => True,
        '校友(未审核)' => True,
        '冻结' => True,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'eventView' => array(//浏览活动
        '游客' => True,
        '未通过认证' => True,
        '校友(未审核)' => True,
        '冻结' => True,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'eventPublish' => array(//发起活动
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'eventSign' => array(//参加活动
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'comment' => array(//发表评论
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'uploadpic' => array(//发布照片
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'userHome' => array(//浏览个人主页
        '游客' => True,
        '未通过认证' => True,
        '校友(未审核)' => True,
        '冻结' => True,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'picView' => array(//浏览照片
        '游客' => True,
        '未通过认证' => True,
        '校友(未审核)' => True,
        '冻结' => True,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'bbsView' => array(//浏览版块
        '游客' => True,
        '未通过认证' => True,
        '校友(未审核)' => True,
        '冻结' => True,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'bbsPost' => array(//发布新话题
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'classroomHomeView' => array(//浏览班级主页
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
    'weibo' => array(//发布微博
        '游客' => False,
        '未通过认证' => False,
        '校友(未审核)' => False,
        '冻结' => False,
        '校友(已认证)' => True,
        '管理员' => True,
    ),
)
?>
